"""update tables

Revision ID: 0.1.0
Revises: 14c72daea083
Create Date: 2025-07-01 21:11:23.931012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0.1.0'
down_revision = '14c72daea083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variable', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mip_era', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('institution_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('source_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('experiment_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('member_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('table_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('grid', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('grid_label', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('nominal_resolution', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('instance_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('datetime_start', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('datetime_end', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('citation_url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('citation_url')
        batch_op.drop_column('datetime_end')
        batch_op.drop_column('datetime_start')
        batch_op.drop_column('instance_id')
        batch_op.drop_column('title')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('nominal_resolution')
        batch_op.drop_column('grid_label')
        batch_op.drop_column('grid')
        batch_op.drop_column('table_id')
        batch_op.drop_column('member_id')
        batch_op.drop_column('experiment_id')
        batch_op.drop_column('source_id')
        batch_op.drop_column('institution_id')
        batch_op.drop_column('mip_era')
        batch_op.drop_column('variable')

    # ### end Alembic commands ###
